---
homebrew_taps:
  - { tap: caskroom/cask }
  - { tap: homebrew/binary }
  - { tap: homebrew/dupes }
  - { tap: caskroom/fonts }
  - { tap: caskroom/versions }
  - { tap: sanemat/font }
  - { tap: kevwil/patches }
  - { tap: bfontaine/utils }
  - { tap: caarlos0/antibody }
  - { tap: caius/jo }
  - { tap: classmethod/repos }

homebrew_cask_packages:
  - { name: iterm2 }
  - { name: google-chrome }
  - { name: slack }
  - { name: github-desktop }
  - { name: docker }
  - { name: visual-studio-code }
  - { name: karabiner-elements }
  - { name: google-japanese-ime }
  - { name: gyazo }
  - { name: franz }

homebrew_packages:
  - { name: ghq, install_options: completions }
  - { name: pcre }
  - { name: libxml2 }
  - { name: glib }
  - { name: fontconfig }
  - { name: readline }
  - { name: openssl }
  - { name: python }
  - { name: python3 }
  - { name: coreutils }
  - { name: git }
  - { name: fish }
  - { name: wget }
  - { name: curl }
  - { name: cmake }
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: ctags }
  - { name: tree }
  - { name: nkf }
  - { name: jq }
  - { name: go }
  - { name: direnv }
  - { name: peco }
  - { name: hub }
  - { name: rbenv }
  - { name: ruby-build }
  - { name: rbenv-binstubs }
  - { name: w3m }
  - { name: tmux }
  - { name: reattach-to-user-namespace }
  - { name: sha2 }
  - { name: xz }
  - { name: lua }
  - { name: neovim/neovim/neovim }
  - { name: pyenv }
  - { name: pyenv-virtualenv }
  - { name: plenv }
  - { name: perl-build }
  - { name: urlview }
  - { name: rfc }
  - { name: mobile-shell }
  - { name: xhyve }
  - { name: ricty }
  - { name: fpp }
  - { name: bash }
  - { name: antibody }
  - { name: freetype }
  - { name: procmail }
  - { name: argon/mas/mas }
  - { name: watch }
  - { name: unar }
  - { name: jo }
  - { name: aurl }
  - { name: gnu-sed }
  - { name: gifsicle }
  - { name: ffmpeg }
  - { name: terraform }
  - { name: packer }
  - { name: consul }
  - { name: vault }
  - { name: docker-completion }
  - { name: docker-compose-completion }
  - { name: nodebrew }
